# Maze Generator
![Screenshot of maze generated by program](screen.png)
This simple maze generator was programmed as an assignment job. This is original project, not changed
## About algorithm
The algorithm used is a mix of Aldous-Broder and Wilson's algorithm. The maze generator class provides easy interface to generate maze data
which later can be used in generating images or 3D levels  
This implementation uses SFML to visualize generated maze, but this can be applied everywhere if proper implementation is written
## Various mazes generated by algorithm
![Small maze generated by program](small.png)
![Medium maze generated by program](medium.png)
![Big maze generated by program](big.png)
